source :rubygems

gem "rails", "3.1.1"
gem "json"
gem "jquery-rails"
gem "mysql"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
  gem "compass", "~> 0.12.alpha"
end

gem "app_config", :git => "git://github.com/die-antwort/app_config.git"
gem "formtastic", "~> 2.0.0"
gem "airbrake"
gem "will_paginate", "~> 3.0"

# Optional gems (from Rails 3.1 default Gemfile):

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'


# More optional gems that we use quite often

# gem "paperclip"
# gem "carrierwave"
# gem "devise"
# gem "cancan"


## RMagick as used by RefineryCMS, to make sure it works on Windows
#rmagick_options = { :require => false }
#if Bundler::WINDOWS
#  rmagick_options.merge!(:git => 'git://github.com/refinerycms/rmagick.git', :branch => 'windows')  
#end
#gem "rmagick", "2.12.0", rmagick_options

# RSpec needs to be in :development group to expose generators
# and rake tasks without having to type RAILS_ENV=test.
group :development, :test do
  gem "rspec-rails", "~> 2.6.0"
end

group :test do
  gem "akephalos", :git => "git://github.com/die-antwort/akephalos.git"
  gem "cucumber-rails"
  gem "factory_girl_rails"
  gem "capybara"
  gem "database_cleaner"
  gem "launchy"
  gem "timecop"
end
