source :rubygems

gem "rails", "3.0.4"
gem "mysql"

gem "app_config", :git => "git://github.com/die-antwort/app_config.git"
gem "compass", "~> 0.10.6"
gem "formtastic", ">= 1.2.1"
gem "hoptoad_notifier"
gem "sprockets", "~> 1.0.2"
gem "will_paginate"


# Uncomment if you want to use any of those

#gem "paperclip"
#gem "carrierwave"
#gem "devise"

## RMagick as used by RefineryCMS, to make sure it works on Windows
#rmagick_options = { :require => false }
#if Bundler::WINDOWS
#  rmagick_options.merge!(:git => 'git://github.com/refinerycms/rmagick.git', :branch => 'windows')  
#end
#gem "rmagick", "2.12.0", rmagick_options

# RSpec needs to be in :development group to expose generators
# and rake tasks without having to type RAILS_ENV=test.
group :development, :test do
  gem "rspec-rails", "~> 2.4.0"
end

group :test do
  gem "akephalos", :git => "git://github.com/die-antwort/akephalos.git"
  gem "cucumber-rails"
  gem "factory_girl_rails"
  gem "capybara"
  gem "database_cleaner"
  gem "launchy"
  gem "timecop"
end
